/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountActions: typeof import('./src/components/AccountActions.vue')['default']
    AccountAdd: typeof import('./src/components/AccountAdd.vue')['default']
    AccountItem: typeof import('./src/components/AccountItem.vue')['default']
    AccountList: typeof import('./src/components/AccountList.vue')['default']
    Button: typeof import('primevue/button')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
